services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CI=true
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - ./.wrangler/state:/app/.wrangler/state
    command: pnpm dev

volumes:
  app_node_modules:
